### ISSUE TITLE
Days filter

### ISSUE THREAD

**Issue by racuna** [ChristopherRogers1991/ExerciseReminders#5]
Hi, I'm just trying this new app. Just what I was looking for. Thank you very much,

For now, the only thing I could suggest is th possibility to filter what days I want to get alarms. Like Monday to Friday for example. My use case is to get an alarm to move and prevent excess sitting while I'm working. But those alarms are useful for me only on workdays.

Thank you very much.
Roberto

**Comment by ChristopherRogers1991** [comment]
Hello Roberto,

Thank you for the suggestion. This is something I've been thinking about doing, but haven't sat down to do it yet. Knowing someone else would use it is a good motivator, though, so I'll see if I can knock it out some time this week.

-Chris

**Comment by racuna** [comment]
Awesome. Thanks. 

BTW, I'm using a Redmi Note with MIUI, wich is infamous to kill apps in the background. I enabled "autostart" and disabled every battery restrictions to test your app properly. Thanks you very much.

**Comment by ChristopherRogers1991** [comment]
In theory, I think it should work consistently, even in that environment. The app uses Android's alarm system, rather than a background process. Each time the "alarm" goes off, it schedules the next one, and then it's just up to the OS to handle it.

If you do experience issues with the alerts not triggering though, please let me know.

**Comment by ChristopherRogers1991** [comment]
I've just published release [1.7.0](https://github.com/ChristopherRogers1991/ExerciseReminders/releases/tag/1.7.0), which adds a day selector. If you have installed via the Play store or the F-droid store, it may take up to a week for the update to go live in the stores.

![05-manage_alarms](https://github.com/ChristopherRogers1991/ExerciseReminders/assets/8608191/e569551d-4225-47a9-a912-81e568bd429b)

**Comment by ChristopherRogers1991** [comment]
Let me know if you have any issues using it.
